
stages:
  - build
  - deploy

build freesia:
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - freesia
  script:
    - yarn install
    - node —max_old_space_size=4096

deploy freesia:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - freesia
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/. ~/front-deployment
