
stages:
  - build
  - deploy

build freesia:
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - freesia
  script:
    - npm install
    - npm run build
deploy freesia:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - freesia
  script:
    - mkdir -p ~/front=deployment
    - rm -rf ~/front=deployment/*
    - cp -r dist/. ~/front=deployment

